## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
##
## rxyhn's starship based configuration
## The minimal, blazing-fast, and infinitely customizable prompt for any shell!

format = """$directory
$character
"""
right_format = """$git_branch$git_status$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 5000

[line_break]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold yellow)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = " [](fg:#262626 bg:none)[$duration ]($style)[](fg:#9ec49f bg:#262626)[󰞌](fg:#262626 bg:#9ec49f)[](fg:#9ec49f bg:none)"
disabled = true
style = "fg:#f0f0f0 bg:#262626"

[directory]
#format = " [](fg:#262626 bg:none)[$path ]($style)[](fg:#6791c9 bg:#262626)[󰍎](fg:#262626 bg:#6791c9)[](fg:#6791c9 bg:none)"
#style = "fg:#f0f0f0 bg:#262626"
format = "[$path](bold green)"
truncation_length = 3
truncate_to_repo=false
disabled = false

[git_branch]
format = " [](fg:#262626 bg:none)[$branch ]($style)[](fg:#ceb188 bg:#262626)[󰘬](fg:#262626 bg:#ceb188)[](fg:#ceb188 bg:none)"
style = "fg:#f0f0f0 bg:#262626"

[git_status]
format= " [](fg:#262626 bg:none)[$all_status$ahead_behind]($style)[](fg:#67afc1 bg:#262626)[󰊤](fg:#262626 bg:#67afc1)[](fg:#67afc1 bg:none)"
style = "fg:#f0f0f0 bg:#262626"
conflicted = "="
ahead =	"󱦲${count} "
behind = "󱦳${count} "
diverged = "󱦲${ahead_count} 󱦳${behind_count} "
up_to_date = "󰄭  "
untracked = "?${count} "
stashed = "󰏖 "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "-${count} "

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
