#!/bin/bash

user="$(whoami)@$(hostnamectl | awk 'FNR==1 {print $3}')"
kernel="$(uname -r)"
os="$(cat /etc/os-release | awk 'NR==1' | awk -F '"' '{print $2}')"
pkgs="$(yay -Q | wc -l)"
wm="$XDG_CURRENT_DESKTOP"

if ! updates_arch=$(checkupdates 2>/dev/null | wc -l) ; then
  updates_arch=0
fi

if ! updates_aur=$(yay -Qum 2>/dev/null | wc -l); then
  updates_aur=0
fi

updates=$((updates_arch + updates_aur))

echo '{"user": "'$user'", "kernel": "'$kernel'", "os": "'$os'", "wm": "'$wm'", "pkgs": "'$pkgs'", "updates": "'$updates'"}'