#!/bin/bash

playerctl metadata --format \
  $'{{position}}\t{{mpris:length}}\t{{title}}\t{{artist}}\t{{album}}\t{{playerName}}\t{{status}}\t{{mpris:artUrl}}\t{{duration(position)}}\t{{duration(mpris:length)}}\t{{shuffle}}\t{{loop}}' |
  while IFS=$'\t' read -r p l title artist album player status artUrl position length shuffle loop; do

    p=$(echo "$p" | sed 's/.\{6\}$//')
    l=$(echo "$l" | sed 's/.\{6\}$//')

    title=${title//\"/\\\"}
    artist=${artist//\"/\\\"}
    album=${album//\"/\\\"}

    printf '{"title": "%s", "artist": "%s", "album": "%s", "player": "%s", "status": "%s", "artUrl": "%s", "position": "%s", "length": "%s", "shuffle": "%s", "loop": "%s", "p": "%s", "l": "%s"}\n' \
      "$title" "$artist" "$album" "$player" "$status" "$artUrl" "$position" "$length" "$shuffle" "$loop" "$p" "$l"
  done
