#!/bin/bash

window_class() {
  echo $(hyprctl activewindow -j | jq --raw-output .class)
}

window_title() {
  echo $(hyprctl activewindow -j | jq --raw-output .title)
}

case $1 in 
--window)
  window_class
  socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    window_class
  done
  ;;
esac

NUMBER_OF_WORKSPACES=6

workspaces(){
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
	seq 1 $NUMBER_OF_WORKSPACES | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

current_workpace(){
  current="$(hyprctl -j monitors | jq '.[0].activeWorkspace.id')"
  eww update current="$current"
}

case $1 in
--workspaces)
  current_workpace
  workspaces
  socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    workspaces
    current_workpace
  done
  ;;
esac
